### ISSUE TITLE
Appbar overrides several unrelated UI settings

### ISSUE THREAD

**Issue by XtraButtery** [xaukael/taskbar#5]
> Environment Details:
> Appbar 0.1.15
> ForgeVTT
> Chromium-based Browser

When using Appbar several unrelated UI elements are overwritten which alter functionality outside the scope of the original module and in some cases outright remove or harm functionality.

When opening the Module Management with Appbar installed the filters for "All Modules | Active Modules | Inactive Modules" does not appear.

Through testing I have discovered that these filters can be made to appear by attempting to re-open the Module Management window while it is open.

![image](https://user-images.githubusercontent.com/35461692/164972555-bf9eb8dd-dde8-47e9-9713-1aacc1a70c87.png)
![image](https://user-images.githubusercontent.com/35461692/164972567-abbca283-d54d-48a1-90ef-9e7c9192024d.png)

On all character sheets the taskbar options are no longer captioned and only retain their icons when Appbar is installed. The character sheet (using Tidy5E Sheet 0.5.26, however this was tested without Tidy5E Sheet and the issue still persisted)

![image](https://user-images.githubusercontent.com/35461692/164972517-9f40ff44-e99d-49c7-bc55-fcab6b5e1775.png)

This occurs on all character sheets, however when using the Tidy5E Sheet another issue presents itself where the various tabs/pages are invisble and most the the text that would normally be displayed on the sheet is instead rendered invisible. The character sheet as it appears with Appbar installed is pictured below.

![image](https://user-images.githubusercontent.com/35461692/164972487-9809e4ac-0667-4c9c-82ea-1e8b60267299.png)

The tabs otherwise appear to be functional and can be accessed however they are otherwise invisble.

![image](https://user-images.githubusercontent.com/35461692/164972799-2893f5f0-e1e8-48f7-919b-014ff34a4ee2.png)

Through testing I have discovered that altering text on the sheet (such as the gender as pictured below) restores the missing UI elements from the character sheet as pictured below, however the issue with the taskbar still remains.

This same issue can also be seen on the Prototype token menu where most of the text has disappeared making the UI practically unusable. Unlike the Tidy5E Sheet altering text in this windows does not restore the missing elements.

![image](https://user-images.githubusercontent.com/35461692/164972856-b0a33523-5905-4498-99d7-57a3b918c3dc.png)

**Comment by xaukael** [comment]
Major code mistake on my part, 0.1.16 should fix

**Comment by XtraButtery** [comment]
This update fixes the visual bugs of text disappearing, however it doesn't seem to address the other overrides with regards to the taskbar where text is changed to icons and cannot be reverted as far as I can tell.

![image](https://user-images.githubusercontent.com/35461692/164986688-d860b56f-51db-405e-97e8-1af7ef7d579c.png)
![image](https://user-images.githubusercontent.com/35461692/164986699-35a33a8f-84d5-41ad-a83f-2c1195fbeef7.png)

Since there is also no alt-text for these icons it is impossible to tell what they do from a glance without already being familiar with the workings of Foundry.

This change to the UI also seems to be outside of the scope of "Appbar" as it instead is leaning into a complete UI overhaul for a much more simplified design. It could also create potential conflicts with other modules later down the line if they do anything to alter the taskbar themselves.

**Comment by xaukael** [comment]
I made the decision to remove the text from the header buttons because adding a minimize button and a pin button for documents was requested and then I realized that cluttered the header for many narrower windows. I plan to make this change optional and togglable in the settings, I just did not get that part done yesterday.

**Comment by xaukael** [comment]
The option should be in there in the 0.1.17 update. I was wanting your opinion on a middle grounds I was thinking of as well. What if I just removed the text from close, minimize, and pin. I will also be looking for a way to add the helper hover text on buttons if that helps.
