### ISSUE TITLE
Issues with GM Screen integration.

### ISSUE THREAD

**Issue by XtraButtery** [xaukael/taskbar#6]
When GM Screen and Appbar are installed simultaneously Appbar replaces GM Screen's usual UI with an integrated button instead, as pictured below.

![image](https://user-images.githubusercontent.com/35461692/164973164-43167476-5e30-4ba9-9855-25432d9f1d0a.png)

When opening the GM Screen using this button however the original button from the GM Screen module re-appears as pictured below.

![image](https://user-images.githubusercontent.com/35461692/164973131-ac84a46a-5675-41a9-8839-3d291e767c62.png)

If the GM Screen UI is then closed using the new taskbar button the original GM Screen UI will persist.

![image](https://user-images.githubusercontent.com/35461692/164973233-5c085a3b-349e-4484-b588-2fa96e142648.png)

Interacting with the original GM Screen button will cause it to disappear, if the GM Screen was first opened and then minimised using the Appbar button before being opened using the original GM Screen button the GM Screen will open with the GM Screen button hidden (as it is likely intended to appear with the Appbar integration)

![image](https://user-images.githubusercontent.com/35461692/164973300-2b980f46-f52b-4469-af37-dd8a83063bd7.png)

**Comment by xaukael** [comment]
That was a bit of an oversight on my part. I use the move sidebar tabs option that shoves that icon way over to where it is underneath the gm screen, making the GM screen button the only way to close it.

**Comment by xaukael** [comment]
I think I fixed it in 0.1.20, let me know if the fix is satisfactory.
