### ISSUE TITLE
New update broke the module

### ISSUE THREAD

**Issue by roi007leaf** [xaukael/taskbar#7]
Uncaught (in promise) TypeError: Hooks._hooks.updateTaskbarClasses is not iterable
    at appbar.js:31:28

this started since last update

**Comment by roi007leaf** [comment]
This seems to have started at 0.19
0.17 seems to work fine

**Comment by xaukael** [comment]
try 0.1.21 and let me know asap

**Comment by roi007leaf** [comment]
Great a fast fix!
